version: "3.8"

services:
  db:
    image: postgres
    restart: always
    shm_size: 128mb
    volumes:
      - ./data:/var/lib/postgresql/data
    ports:
      - "8081:5432"
    env_file:
      - .env

  adminer:
    image: adminer
    restart: always
    ports:
      - "8080:8080"
